### ISSUE TITLE
Failure summary is not shown

### ISSUE THREAD

**Issue by gervaisb** [albuch/sbt-dependency-check#224]
Hello,

We are using your plugin to analyze our dependencies and fail our CI in case of vulnerability. However, it seems that the failure summary is not shown; Sbt fails with a quite vague error message:
> [error] Vulnerability with CVSS score higher 7.0 found. Failing build.

After digging into the sources, I have seen this line that should print the summary but the log message is never shown:

https://github.com/albuch/sbt-dependency-check/blob/b2658b1422e3bbb87616e5ffe47d5e7968cf3e1c/src/main/scala/net/vonbuchholtz/sbt/dependencycheck/DependencyCheckPlugin.scala#L595

Do we have to provide a specific logger configuration somewhere ?

Thanks

**Comment by albuch** [comment]
This is an issue since SBT 1.x: https://github.com/sbt/sbt/issues/3398 
See #67 for reference as well.
Please follow the instructions in the readme on logging levels to enable logging of the core library: ﻿﻿https://github.com/albuch/sbt-dependency-check#changing-log-level

**Comment by gervaisb** [comment]
Indeed. Thanks a lot for your work.

**Comment by fcv** [comment]
My 2cents,

Instead of using `-Dlog4j2.level=debug` as suggested by [the documentation](https://github.com/albuch/sbt-dependency-check/tree/e5d9a780e080ba0755150b52efea8803a068770b#changing-log-level), which leads to a lot of output, I could make it work by [programmatically changing](https://logging.apache.org/log4j/2.x/manual/customconfig.html#Programmatically_Modifying_the_Current_Configuration_after_Initialization) the Level configuration of the `org.owasp.dependencycheck.agent.DependencyCheckScanAgent` logger specifically. For example: 

```scala
initialize ~= { _ =>
  val loggerName = classOf[DependencyCheckScanAgent].getName
  val ctx = LogManager.getContext(false).asInstanceOf[LoggerContext]
  val config = ctx.getConfiguration
  config.addLogger(
    loggerName,
    LoggerConfig.createLogger(
      /* additivity = */ true,
      /* level = */ org.apache.logging.log4j.Level.WARN,
      /* loggerName = */ loggerName,
      /* includeLocation = */ "true",
      /* refs = */ new Array[AppenderRef](0) ,
      /* properties = */ new Array[Property](0),
      /* config = */ config,
      /* filter = */ null)
  )
  ctx.updateLoggers()
}
```

I hope it helps.
