### ISSUE TITLE
dependencyCheckSuppressionFile doesn't seem to do anything

### ISSUE THREAD

**Issue by mdedetrich** [albuch/sbt-dependency-check#237]
#### Describe the bug
I am attempting to use `dependencyCheckSuppressionFile` to point to an xml file with the suppression standard and it doesn't seem to be doing anything

#### Version of sbt-dependency-check used
The problem occurs using version 3.4.0 of the the plugin.

#### Log file
https://gist.github.com/mdedetrich/019cc64a4d1158b2d277a86f81224cb4

#### To Reproduce
1. Go to https://github.com/aiven/guardian-for-apache-kafka/pull/130 and checkout the branch
2. Run `sbt dependencyCheckAggregate`
3. Open `dependency-check/dependency-check-report.html`

#### Expected behavior
The generated `dependency-check/dependency-check-report.html` shouldn't have any vulnerabilities listed due to actively suppressing them.

#### Additional context
Maybe its specific to `dependencyCheckSuppressionFile`?

Also the `suppression.xml` file was derived from the generated report which has suppress button, i.e.
![image](https://user-images.githubusercontent.com/2337269/156320874-282d66ca-17a7-48a4-90c6-2f870be18568.png)

**Comment by albuch** [comment]
Hi @mdedetrich,
I've tested with your branch, ran `dependencyChecklAggregate` and everything works as expected. You've declared one suppression for `akka-stream-json` which is displayed in the report in the top statistic: `Vulnerabilities suppressed: 1` as well as under section `Suppressed Vulnerabilities` at the bottom of the file (click on the headline to see all suppressed vulnerabilities). 
You need to declare another suppression rule for `akka-stream-circe` if you want that suppressed too.

You can additionally [report this as a false-postive](https://github.com/jeremylong/DependencyCheck/issues/new?assignees=&labels=FP+Report&template=false-positive-report.yml&title=%5BFP%5D%3A+) at the upstream project so that it will be included in a future release for all users of DependencyCheck.

**Comment by mdedetrich** [comment]
Thanks, I just realized I mistook the names and yes I can confirm that everything is working correctly. Apologies for wasting your time.
