### ISSUE TITLE
MySQL Server vulnerabilities false positive in mysql-connector-java

### ISSUE THREAD

**Issue by davidbernick** [albuch/sbt-dependency-check#5]
A project I have uses MySQL's Connector/J for JDBC. When I use the plugin, it identifies the MySQL JDBC driver artifact as being vulnerable, but all of the referenced vulnerabilities are for the MySQL server application and not in any way related to the JDBC driver.

**Comment by jeremylong** [comment]
@davidbernick This is unfortunately one of the common types of false positives. To best understand why this is happening I would suggest reading the following three articles:

* [How does dependency-check work?](http://jeremylong.github.io/DependencyCheck/general/internals.html)
* [How to read the report](http://jeremylong.github.io/DependencyCheck/general/thereport.html)
* [Suppressing False Positives](http://jeremylong.github.io/DependencyCheck/general/suppression.html)

Several of the false positives that have been reported have been resolved in the core engine; either through tuning the matching algorithms or adding entries to the base suppression file included in dependency-check. However, we have decided not to put in base suppression rules for the JDBC drivers. Using the report it is simple enough to suppress these in your local environment; however, these findings may point out that you are using an older, vulnerable version of MySQL.

Also, in the future if you find false positives please report them to the [core dependency-check](https://github.com/jeremylong/DependencyCheck) project. The SBT plugin is just a wrapper around the core engine and in most cases any bugs that crop up are likely due to the core engine.

**Comment by albuch** [comment]
Thanks @jeremylong, I'll add a section to the docs where to report false positives/negatives in the next release.

**Comment by jeremylong** [comment]
@albuch consider adding an issue template (see https://github.com/jeremylong/DependencyCheck/tree/master/.github and https://help.github.com/articles/creating-an-issue-template-for-your-repository/) or the contributor guidelines file (see https://help.github.com/articles/setting-guidelines-for-repository-contributors/).

--Jeremy

**Comment by albuch** [comment]
I've added an issue template. Closing this issue.
