### ISSUE TITLE
Override on guava still reported on avro-1.8.2.jar (shaded: com.google.guava:guava:11.0.2)

### ISSUE THREAD

**Issue by reidrac** [albuch/sbt-dependency-check#62]
dependencyCheck reports a vulnerability on a transitive dependency, and when the version of the transitive dependency is bumped via dependencyOverrides, the problem still shows in the report.

The tool reports a vulnerability (CVE-2018-10237) in guava 11.0.2, because of avro 1,8.2.

Guava was updated to 27.0-jre, from my `build.sbt`:
```
dependencyOverrides += "com.google.guava" % "guava" % "27.0-jre"
```

I've added a suppression on `cpe:/a:google:guava:11.0.2`.

Thanks!

**Comment by albuch** [comment]
@reidrac Could you tell me which dependency contains the vulnerable guava version so that I can reproduce the issue?

**Comment by albuch** [comment]
As far as I understand it this is not a false positive that can and should be handled/filtered by dependency-check automatically.
You are overriding the the guava package in the classpath, but you still retain the shaded classes that were copied from the vulnerable guava version in your classpath.

You should therefore analyze if the attack vector of the CVE is exploitable via the shaded classes or not. If so report them to the avro maintainers to apply a fix. If not go with the local suppression that you are already using.

I'll double check with the folks of dependency-check-core though if they think otherwise.

**Comment by albuch** [comment]
Yes, though it still contains the pom.xml of the shaded guava version, whcih is indexed by dependency-check as well.
A side not on your suppression: you shouldn't exclude the CPE for guava though, because when you re-introduce a vulnerable guava version later on it wouldn't be reported.
You should rather exclude the pom.xml file in the meta-inf directory.
```
<suppress>
    <filePath regex="true">.*\bMETA-INF\b.*\/guava\/pom\.xml$</filePath>
    <cve>CVE-2018-10237</cve>
</suppress>
```

**Comment by reidrac** [comment]
Lovely, thanks for the tip!
