### ISSUE TITLE
Usage of inAnyProject filter confusing in dependencyCheckAggregate

### ISSUE THREAD

**Issue by AndyKirsch** [albuch/sbt-dependency-check#95]
In the dependencyCheckAggregate task it is using the [inAnyProject filter](https://github.com/albuch/sbt-dependency-check/blob/master/src/main/scala/net/vonbuchholtz/sbt/dependencycheck/DependencyCheckPlugin.scala#L371-L375) ([docs](https://www.scala-sbt.org/1.x/docs/Tasks.html#More+on+filter+construction)) which attempts to aggregate across all subprojects not just those aggregated in the sbt configuration.

Would swapping out the usage of inAnyProject to inAggregates break some other use case?

**Comment by albuch** [comment]
The dependency-check terminology for aggregate has a different meaning than in the sbt context.
The aggregate term comes form the original Maven Plugin where the behaviour is to include all modules of a pom.xml in one single aggregated report. That is why the task is called `dependencyCheckAggregate` and why we use `inAnyProject` as we want to mimic the same behaviour as in the Maven build.

As for limiting sbt-dependency-check to only aggregate sbt projects: is this a use case you explicitly need? What is the downside to scanning all projects instead of only the aggregated?

**Comment by AndyKirsch** [comment]
In this specific case we've got a different sbt plugin that hooks the update event and checks for certain kinds of evictions. Running `sbt dependencyCheckAggregate` was causing the other plugin to halt things while`sbt compile` did not. It is more of a confusion of expectations rather than an explicit need.

**Comment by AndyKirsch** [comment]
I put together https://github.com/AndyKirsch/dependency-check-repro to show the issue `sbt update` works `sbt dependencyCheckAggregate` does not

**Comment by albuch** [comment]
Thanks for the example project @AndyKirsch, I'll have a look at it end of next week.

**Comment by albuch** [comment]
I've put some time into recapturing my initial thinking for the aggregate task, and I think (thats what the documentation of the tasks says anyway) that the aggregate task should only pick up aggregate projects and their dependencies, like you suggested.
Additionally I'll will either define a new task to aggregate reports over inAnyProject or a setting to switch between inAnyProject and aggregates.

As this will be a breaking change for the `dependencyCheckAggegrate` task either way, as the default will be only aggregates, we'll prepare a new major release for that.
